[OHOS ERROR] ld.lld: error: duplicate symbol: set_pwm_period
[OHOS ERROR] >>> defined at buzzer.c:40 (../../my_sample/test_sample/buzzer/src/buzzer.c:40)
[OHOS ERROR] >>>            obj/my_sample/test_sample/buzzer/src/buzzer_test/buzzer.o:(set_pwm_period)
[OHOS ERROR] >>> defined at um_pwm.c:41 (../../my_sample/test_sample/buzzer/src/um_pwm.c:41)
[OHOS ERROR] >>>            obj/my_sample/test_sample/buzzer/src/buzzer_test/um_pwm.o:(.text.set_pwm_period+0x1)
[OHOS ERROR] 
[OHOS ERROR] ld.lld: error: duplicate symbol: set_pwm_dutyCycle
[OHOS ERROR] >>> defined at buzzer.c:47 (../../my_sample/test_sample/buzzer/src/buzzer.c:47)
[OHOS ERROR] >>>            obj/my_sample/test_sample/buzzer/src/buzzer_test/buzzer.o:(set_pwm_dutyCycle)
[OHOS ERROR] >>> defined at um_pwm.c:75 (../../my_sample/test_sample/buzzer/src/um_pwm.c:75)
[OHOS ERROR] >>>            obj/my_sample/test_sample/buzzer/src/buzzer_test/um_pwm.o:(.text.set_pwm_dutyCycle+0x1)
[OHOS ERROR] 
[OHOS ERROR] ld.lld: error: duplicate symbol: set_pwm_enable
[OHOS ERROR] >>> defined at buzzer.c:54 (../../my_sample/test_sample/buzzer/src/buzzer.c:54)
[OHOS ERROR] >>>            obj/my_sample/test_sample/buzzer/src/buzzer_test/buzzer.o:(set_pwm_enable)
[OHOS ERROR] >>> defined at um_pwm.c:145 (../../my_sample/test_sample/buzzer/src/um_pwm.c:145)
[OHOS ERROR] >>>            obj/my_sample/test_sample/buzzer/src/buzzer_test/um_pwm.o:(.text.set_pwm_enable+0x1)
[OHOS ERROR] clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
[OHOS ERROR] Traceback (most recent call last):
[OHOS ERROR]   File "/home/joejoe333/ohos4.0release/build/hb/services/ninja.py", line 49, in _execute_ninja_cmd
[OHOS ERROR]     SystemUtil.exec_command(
[OHOS ERROR]   File "/home/joejoe333/ohos4.0release/build/hb/util/system_util.py", line 63, in exec_command
[OHOS ERROR]     raise OHOSException(
[OHOS ERROR] exceptions.ohos_exception.OHOSException: Please check build log in /home/joejoe333/ohos4.0release/out/unionpi_tiger/build.log
[OHOS ERROR] 
[OHOS ERROR] During handling of the above exception, another exception occurred:
[OHOS ERROR] 
[OHOS ERROR] Traceback (most recent call last):
[OHOS ERROR]   File "/home/joejoe333/ohos4.0release/build/hb/containers/status.py", line 47, in wrapper
[OHOS ERROR]     return func(*args, **kwargs)
[OHOS ERROR]   File "/home/joejoe333/ohos4.0release/build/hb/modules/ohos_build_module.py", line 67, in run
[OHOS ERROR]     raise exception
[OHOS ERROR]   File "/home/joejoe333/ohos4.0release/build/hb/modules/ohos_build_module.py", line 65, in run
[OHOS ERROR]     super().run()
[OHOS ERROR]   File "/home/joejoe333/ohos4.0release/build/hb/modules/interface/build_module_interface.py", line 72, in run
[OHOS ERROR]     raise exception
[OHOS ERROR]   File "/home/joejoe333/ohos4.0release/build/hb/modules/interface/build_module_interface.py", line 70, in run
[OHOS ERROR]     self._target_compilation()
[OHOS ERROR]   File "/home/joejoe333/ohos4.0release/build/hb/modules/ohos_build_module.py", line 103, in _target_compilation
[OHOS ERROR]     self.target_compiler.run()
[OHOS ERROR]   File "/home/joejoe333/ohos4.0release/build/hb/services/ninja.py", line 38, in run
[OHOS ERROR]     self._execute_ninja_cmd()
[OHOS ERROR]   File "/home/joejoe333/ohos4.0release/build/hb/services/ninja.py", line 52, in _execute_ninja_cmd
[OHOS ERROR]     raise OHOSException('ninja phase failed', '4000')
[OHOS ERROR] exceptions.ohos_exception.OHOSException: ninja phase failed
[OHOS ERROR] 
[OHOS ERROR] Code:      4000
[OHOS ERROR] 
[OHOS ERROR] Reason:    ninja phase failed